import pl.poznan.put.cs.si.puttalky.*;
import java.util.Set;
import java.util.Arrays;
import java.util.HashSet;

rule "start"
	salience 3
	
	when
		not Fakt(nazwa=="start")
		zamowienie : Zamowienie()
	then
		zamowienie.powitanie();
		System.out.println();
		System.out.println();
		insert(new Fakt("start", "0"));
end

rule "Podaj dodatki"
	salience 2
	
	when
		not Fakt(nazwa == "wlasny_dodatek")
		not Fakt(nazwa == "dodatek")
		dodatek : Dodatek()
		parser : Parser()
		baza : BazaWiedzy()
	then
		dodatek.setMonit("Jaki dodatek powinna zawierać Twoja pizza?:\n");
		dodatek.zadajPytanie();
		parser.przetworzOdpowiedz();
		
		boolean inserted = false;
  
		for (String slowo : parser.getSlowaKluczowe()){
			for (String uriKlasy : baza.dopasujDodatek(slowo)) { 
		        insert(new Fakt("dodatek", uriKlasy));
		        inserted = true;
		    } 
		}
		
		Set<String> listaDodatkow = new HashSet<String>(Arrays.asList(parser.getSlowaKluczowe()));
		if (!inserted && !listaDodatkow.isEmpty()) {
			String dodatki = String.join(", ", listaDodatkow);
			insert(new Fakt("wlasny_dodatek", dodatki));
		}
		update(dodatek);
end

rule "Podaj rodzaj ciasta"
	salience 2
	
	when
		not Fakt(nazwa == "rodzaj_ciasta")
		ciasto : Ciasto()
		parser : Parser()
	then
        ciasto.setMonit("Podaj rodzaj ciasta:\n");
        ciasto.zadajPytanie();
        parser.przetworzOdpowiedz();
		 
		boolean inserted = false;
		
		for (String slowo : parser.getSlowaKluczowe()){
			if (slowo.equals("cienki")){
		       insert(new Fakt("rodzaj_ciasta", "cienkie"));
		       inserted = true;
			} else if (slowo.equals("gruby")) {
		       insert(new Fakt("rodzaj_ciasta", "grube"));
		       inserted = true;
			}
		}
		
		Set<String> ciastoSet = new HashSet<String>(Arrays.asList(parser.getSlowaKluczowe()));
		if (!inserted && !ciastoSet.isEmpty()) {
			String noweCiasto = String.join(", ", ciastoSet);
			insert(new Fakt("rodzaj_ciasta", noweCiasto));
		}
					
		update(ciasto);
end

rule "Wlasne dodatki"
	when
		$dodatek : Fakt(nazwa == "wlasny_dodatek")
		$ciasto : Fakt(nazwa == "rodzaj_ciasta")
	then
		System.out.println("Przygotujemy specjalną pizzę:");
		System.out.println("  Dodatki: \t" + $dodatek.getWartosc());
		System.out.println("  Ciasto: \t" + $ciasto.getWartosc());
end

rule "Polecana pizza"
	salience 1
	
	when
		Fakt(nazwa == "dodatek") && 
		Fakt(nazwa == "rodzaj_ciasta") && 	
		not Fakt(nazwa == "pizza_propozycja") &&
        $dodatek : Fakt( nazwa == "dodatek")
 		
		baza: BazaWiedzy()
		pizza: Pizza()
	then

		Set<String> pizze = baza.wyszukajPizzePoDodatkach($dodatek.getWartosc());
            
        if (pizze.size()>1){            		
			for (String nazwaPizzy : pizze) {
				insert(new Fakt("pizza_propozycja", nazwaPizzy));
		    	if (!nazwaPizzy.equals("Nothing")){
		       	   System.out.println("Polecam pizzę:"+nazwaPizzy);
		       	}
		    }
		}
		else {
			System.out.println(pizza.getBrakDopasowania());
	    }

end

rule "zakończenie"

	when
		not (Fakt(nazwa == "koniec")) &&
		Fakt(nazwa == "pizza_propozycja") 

		zamowienie : Zamowienie()
	then
		insert(new Fakt("koniec", "0"));
		zamowienie.pozegnanie();
end